### PR TITLE
Update for Wintersmith 2.1

### PR DESCRIPTION
**Pull request by kennethjor**
Just a small maintenance update mainly for Wintersmith 2.1, CoffeeScript 1.9, and the new CDN URL for MathJax.

### CODE REVIEW

**Comment by lhagan** [comment]
Thanks! I actually don't use `wintersmith-pandoc` myself anymore; if you'd like to take ownership of it, I'd be happy to transfer it over. Otherwise, I'm fine with continuing to merge updates like this.

**Comment by kennethjor** [comment]
@lhagan Thanks for merging this in. I just re-implemented my own personal website as Wintersmith and used Pandoc due to its MathJax support. If you're not using it and will not be keeping `wintersmith-pandoc` up-to-date, I'll be happy to take it on from here. I found [an issue here](https://github.com/slevithan/xregexp/issues/11) for transferring ownership of NPM packages as well. Let me know how you want to proceed and we'll sort it out.

**Comment by lhagan** [comment]
That'd be great if you don't mind taking over. Let me know what your npm user name is and I'll complete the transfer.

**Comment by kennethjor** [comment]
Cool. It's the same as my GitHub username: kennethjor

**Comment by lhagan** [comment]
OK - I've added you as an owner on npm, but in order to transfer the github project over you'll need to delete your fork first.

**Comment by kennethjor** [comment]
Thanks, I have deleted my fork.

**Comment by lhagan** [comment]
OK, should be all set. Let me know if you have any problems!

**Comment by kennethjor** [comment]
@lhagan Thanks all done. I have pushed a new maintenance release to NPM and it went without any problems. Do you want to remove yourself as the owner in NPM?

I'll take good care of your baby I promise ;)

**Comment by lhagan** [comment]
Done...thanks again!

**Comment by kennethjor** [comment]
Sweet, that went off without a hitch!

**Pull request merged**
